steps:
- name: "docker.io/library/python:3.6"
  args: ['bash', './cloudBuild/runTestsAndBuild.sh']

- name: 'google/cloud-sdk:251.0.0'
  args:
  - 'bash'
  - './cloudBuild/integrationTests.sh'
  - '${_STAGE}'
  - '${_PROJECT}'
  - '${_LOCATION}'
  - '${_DATASET}'

- name: 'docker.io/library/python:3.6'
  args:
  - 'bash'
  - './cloudBuild/release.sh'
  - '$REPO_NAME'
  - '$TAG_NAME'
  secretEnv: ['GITHUB_TOKEN', 'PYPI_TOKEN']
  
substitutions:
  _STAGE: v1beta1
  _PROJECT: gcp-healthcare-oss-test
  _LOCATION: us-central1
  _DATASET: healthcare-api-dicomweb-cli-test

  
secrets:
- kmsKeyName: projects/gcp-healthcare-oss-test/locations/global/keyRings/default/cryptoKeys/github-robot-access-token
  secretEnv:
    GITHUB_TOKEN: CiQAM/SK3FUc1t+CnHDdgRzbc556FIyHddxRpsnolmSKfpiZ66sSUQDrEGO9gz15JIulryNagWzUOGbBEAaC04y85J8fNRjJZ8T8ntzh6Kt0Sa+GCG+3n5xSQdDJdj6xOG0LfVzvU+/K3mZ1KJlIcd0jiCeBrjYLlw==
    PYPI_TOKEN: PLACEHOLDER
